SistemaVentas.Web/Controllers/CategoriasController.cs
using Api.Web.WebApi.DTO.OperationResult;
using Api.Web.WebApi.DTO.Request;
using Api.Web.WebApi.DTO.Response;
using Api.Web.WebApi.Utilities.Logger;
using Microsoft.AspNetCore.Mvc;
using SistemaVentas.Web.Infrastructure.Core;

namespace SistemaVentas.Web.Controllers
{
    public class CategoriasController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly Logger _Logger;
        string _Url = string.Empty;
        public CategoriasController(IConfiguration configuration)
        {
            _configuration = configuration;
            this._Logger = new Logger(_configuration["EnvApp:LogPath"]);
            _Url = _configuration["Settings:Urlpi"];
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetCategorias()
        {
            var _Result = new object();
            ListCategoriasResponseDTO _Response = new ListCategoriasResponseDTO();
            CoreAdministration _Core = new CoreAdministration(this._Logger);
            //var _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                if (!(_Response = _Core.GetCategorias(_Url)).Result.IsOK())
                    throw new Exception(string.Join(", ", _Response.Result.Errors.Select(x => x.Message)));
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Error : Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
            }
            return PartialView("_PanelResult", _Response);
        }
        [HttpPost]
        public JsonResult SaveCategoria(string _Descripcion)
        {
            var Result = new object();
            //string _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                OperationResult _Response = new OperationResult();
                CoreAdministration _Core = new CoreAdministration(this._Logger);
                if (!(_Response = _Core.SaveCategoria(_Url, _Descripcion)).IsOK())
                    throw new Exception(string.Join(", ", _Response.Errors.Select(x => x.Message)));

                Result = new { Error = string.Empty, IsOK = true, Code = OperationResult.StatusCodesEnum.OK };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(Result);
        }
        [HttpPost]
        public JsonResult UpdateCategoria(UpdateCategoriaRequestDTO _Request)
        {
            var Result = new object();
            //string _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                OperationResult _Response = new OperationResult();
                CoreAdministration _Core = new CoreAdministration(this._Logger);
                if (!(_Response = _Core.UpdateCategoria(_Url, _Request)).IsOK())
                    throw new Exception(string.Join(", ", _Response.Errors.Select(x => x.Message)));
                Result = new { Error = string.Empty, IsOK = true, Code = OperationResult.StatusCodesEnum.OK };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(Result);
        }
        [HttpPost]
        public JsonResult DeleteCategoria(int _IdCategoria)
        {
            var Result = new object();
            //string _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                OperationResult _Response = new OperationResult();
                CoreAdministration _Core = new CoreAdministration(this._Logger);
                if (!(_Response = _Core.DeleteCategoria(_Url, _IdCategoria)).IsOK())
                    throw new Exception(string.Join(", ", _Response.Errors.Select(x => x.Message)));
                Result = new { Error = string.Empty, IsOK = true, Code = OperationResult.StatusCodesEnum.OK };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(Result);
        }
    }
}

SistemaVentas.Web/Controllers/ProductosController.cs
using Api.Web.WebApi.DTO.OperationResult;
using Api.Web.WebApi.DTO.Request;
using Api.Web.WebApi.DTO.Response;
using Api.Web.WebApi.Utilities.Logger;
using Microsoft.AspNetCore.Mvc;
using SistemaVentas.Web.Infrastructure.Core;
using System.Security.Claims;
using static System.Net.Mime.MediaTypeNames;

namespace SistemaVentas.Web.Controllers
{
    public class ProductosController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly Logger _Logger;
        string _Url = string.Empty;

        public ProductosController(IConfiguration configuration)
        {
            _configuration = configuration;
            this._Logger = new Logger(_configuration["EnvApp:LogPath"]);
            _Url = _configuration["Settings:Urlpi"];
        }
        public IActionResult Index()
        {

            return View();
        }
        public IActionResult GetProducts()
        {
            var _Result = new object();
            ListProductsResponseDTO _Response = new ListProductsResponseDTO();
            CoreAdministration _Core = new CoreAdministration(this._Logger);
            //var _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                if (!(_Response = _Core.GetProducts(_Url)).Result.IsOK())
                    throw new Exception(string.Join(", ", _Response.Result.Errors.Select(x => x.Message)));
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Error : Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
            }
            return PartialView("_PanelResult", _Response);
        } 

        public JsonResult GetCategorias()
        {
            var Result = new object();
            //string _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                ListCategoriasResponseDTO _OperationResult = new ListCategoriasResponseDTO();
                CoreAdministration _Core = new CoreAdministration(this._Logger);
                _OperationResult = _Core.GetCategorias(_Url);
                if (_OperationResult.Result.Code == OperationResult.StatusCodesEnum.CONFLICT.ToString("D"))
                    return Json(new { Error = string.Empty, IsOK = false, Code = OperationResult.StatusCodesEnum.CONFLICT });
                if (!_OperationResult.Result.IsOK() && _OperationResult.Result.Code != OperationResult.StatusCodesEnum.ACCEPTED.ToString("D"))
                    throw new Exception(string.Join(", ", _OperationResult.Result.Errors.Select(x => x.Message)));
                Result = new { Error = string.Empty, IsOK = true, Code = OperationResult.StatusCodesEnum.OK, _OperationResult.Items };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(Result);
        }
        [HttpPost]
        public JsonResult SaveProducto(SaveProductoRequestDTO _Request)
        {
            var Result = new object();
            //string _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                OperationResult _Response = new OperationResult();
                CoreAdministration _Core = new CoreAdministration(this._Logger);
                if (!(_Response = _Core.SaveProducto(_Url, _Request)).IsOK())
                    throw new Exception(string.Join(", ", _Response.Errors.Select(x => x.Message)));

                Result = new { Error = string.Empty, IsOK = true, Code = OperationResult.StatusCodesEnum.OK };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(Result);
        }
        [HttpPost]
        public JsonResult UpdateProducto(UpdateProductoRequestDTO _Request)
        {
            var Result = new object();
            //string _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                OperationResult _Response = new OperationResult();
                CoreAdministration _Core = new CoreAdministration(this._Logger);
                if (!(_Response = _Core.UpdateProducto(_Url, _Request)).IsOK())
                    throw new Exception(string.Join(", ", _Response.Errors.Select(x => x.Message)));
                Result = new { Error = string.Empty, IsOK = true, Code = OperationResult.StatusCodesEnum.OK };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(Result);
        }
        [HttpPost]
        public JsonResult DeleteProduct(int _IdProducto)
        {
            var Result = new object();
            //string _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                OperationResult _Response = new OperationResult();
                CoreAdministration _Core = new CoreAdministration(this._Logger);
                if (!(_Response = _Core.DeleteProduct(_Url, _IdProducto)).IsOK())
                    throw new Exception(string.Join(", ", _Response.Errors.Select(x => x.Message)));
                Result = new { Error = string.Empty, IsOK = true, Code = OperationResult.StatusCodesEnum.OK };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(Result);
        }

    }
}

SistemaVentas.Web/Controllers/VentaController.cs
using Api.Web.WebApi.DTO.OperationResult;
using Api.Web.WebApi.DTO.Request;
using Microsoft.AspNetCore.Mvc;
using SistemaVentas.Web.Infrastructure.Core;
using Api.Web.WebApi.Utilities.Logger;
using Api.Web.WebApi.DTO.Response;
using static System.Formats.Asn1.AsnWriter;
using Api.Web.WebApi.DTO;

namespace SistemaVentas.Web.Controllers
{
    public class VentaController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly Logger _Logger;
        string _Url = string.Empty;
        public VentaController(IConfiguration configuration)
        {
            _configuration = configuration;
            this._Logger = new Logger(_configuration["EnvApp:LogPath"]);
            _Url = _configuration["Settings:Urlpi"];
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public JsonResult Autocomplete(string Search)
        {
            var Result = new object();
            //string _CurrentUserName = System.Web.HttpContext.Current.User.Identity.Name;
            try
            {
                ListAutocompleteResponseDTO _Response = new ListAutocompleteResponseDTO();
                CoreAdministration _Core = new CoreAdministration(this._Logger);
                if (!(_Response = _Core.Autocomplete(_Url, Search)).Result.IsOK())
                    throw new Exception(string.Join(", ", _Response.Result.Errors.Select(x => x.Message)));
                Result = new { Error = string.Empty, IsOK = true,_Response.Autocomplete};
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(Result);
        }
        [HttpPost]
        public JsonResult ObtenerProducto(int idproducto)
        {
            var _Result = new object();
            var _Product = new ProductoDTO();
            ListProductsResponseDTO _Response = new ListProductsResponseDTO();
            CoreAdministration _Core = new CoreAdministration(this._Logger);
            try
            {
                if (!(_Response = _Core.GetProducts(_Url)).Result.IsOK())
                    throw new Exception(string.Join(", ", _Response.Result.Errors.Select(x => x.Message)));
                _Product = _Response.Items.Where(x => x.IdProducto == idproducto).FirstOrDefault();
                _Result = new { Error = string.Empty, IsOK = true, _Product };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                _Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(_Result);
        }
        [HttpPost]
        public JsonResult RegisterVentas(SaveVentaRequestDTO _Request)
        {
            var _Result = new object();
            RegistroVentaResponseDTO _Response = new RegistroVentaResponseDTO();
            CoreAdministration _Core = new CoreAdministration(this._Logger);
            try
            {
                if (!(_Response = _Core.RegisterVentas(_Url, _Request)).Result.IsOK())
                    throw new Exception(string.Join(", ", _Response.Result.Errors.Select(x => x.Message)));
                _Result = new { Error = string.Empty, IsOK = true, _Response.NroDocumento };
            }
            catch (Exception ex)
            {
                //this._Logger.LogText("Erorr: Usuario : " + _CurrentUserName);
                this._Logger.LogError(ex);
                _Result = new { Error = ex.Message, IsOK = false, Code = OperationResult.StatusCodesEnum.INTERNAL_SERVER_ERROR };
            }
            return Json(_Result);
        }
    }
}

SistemaVentas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaVentas.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaVentas.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sweetalert2.min.css" />
    <link rel="stylesheet" href="~/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/jquery-ui.min.css" />
    @*<link rel="stylesheet" href="~/css/jquery-ui.theme.css" />*@
    @*<link rel="stylesheet" href="~/css/theme.css" />*@
    @*<link  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">*@
    @*<link rel="stylesheet" href="~/css/font-awesome.css"/>*@


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Inventario
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Categorias" asp-action="Index">Categoria</a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Ventas
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Venta" asp-action="Index">Venta</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" asp-area="" asp-controller="Categorias" asp-action="Index">Detalle</a>
                                </li>
                            </ul>
                        </li>
                                                
                        <li class="nav-item">
                            <a class="nav-link" href="#">About</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-light" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        @*<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SistemaVentas.Web</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
        <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>
        </ul>
        </div>
        </div>
        </nav>*@
    </header>
    <partial name="_Preload"></partial>
    @*@Html.Partial("_Preload")*@
    <div class="container">

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SistemaVentas.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/jquery-ui.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/sweetalert2.min.js" asp-append-version="true"></script>
    <script src="~/js/jquery.blockUI.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SistemaVentas.Web/Views/Shared/_Preload.cshtml
<div class="container">
    <div class="loading-container">
        <div class="loading"></div>
    </div>
</div>